<section id="results">
    <?php $articles = $this->paginator; ?>

    <?php foreach($articles as $article): ?>
        <?php echo $this->partial('partials/_article-mini.phtml', array(
            'article' => $article,
            'term'    => $this->term
        )); ?>
    <?php endforeach; ?>

    <?php echo $this->paginationControl(
        $this->paginator,
        'Sliding',
        'pagination/_control.phtml',
        array(
            'route' => 'search',
            'term'  => $this->term
        )); ?>
</section>