        <?php $viewMore = false; ?>
        <?php $article = $this->article; ?>
        <?php $id = $article->getId(); ?>
        <article>
            <header>
                <h2><?php echo $article->getTitle(); ?></h2>
                <?php $authors = $article->getAuthors(); ?>
                <?php if(empty($authors)): ?>
                    <h3>[No authors listed]</h3>
                <?php else: ?>
                    <h3><?php echo implode(", ", $authors); ?></h3>
                <?php endif; ?>
            </header>
            <?php $abstract = $article->getAbstract(); ?>
            <?php if(count($abstract)): ?>
                <div class="abstract">
                    <h3>Abstract</h3>
                <?php $abstract_content = implode(" ", $abstract); ?>
                <?php $abstract_truncated = $this->truncate($abstract_content); ?>
                <?php if(($abstract_content != $abstract_truncated) || count($abstract) > 1) {
                    $viewMore = true;
                } ?>
                    <p><?php echo $abstract_truncated; ?></p>
                </div>
            <?php endif; ?>
            <div id="article-actions">
                <?php if($viewMore): ?>
                    <p class="read-more"><a href="<?php echo $this->url('search', array('term' => $id)); ?>">Read more</a></p>
                <?php endif; ?>
                <?php if(!$this->citations()->isAdded($article)): ?>
                <p class="add-to-list">
                        <?php $redirectUrl = $this->url('search', array('term' => $this->term)); ?>
                        <?php $addUrl = $this->url('citation/add', array('id' => $id)); ?>
                        <?php $addUrl .= '?redirect=' . $redirectUrl; ?>
                    <a href="<?php echo $addUrl; ?>">Add to list</a>
                </p>
                <?php else: ?>
                <p class="remove-from-list">
                    <?php $redirectUrl = $this->url('search', array('term' => $this->term)); ?>
                    <?php $delUrl = $this->url('citation/remove', array('id' => $id)); ?>
                    <?php $delUrl .= '?redirect=' . $redirectUrl; ?>
                    <a href="<?php echo $delUrl; ?>">Remove from list</a>
                </p>
                <?php endif; ?>
            </div>
            <footer>
                <p class="pmid"><b>PMID:</b> <a href="http://www.ncbi.nlm.nih.gov/pubmed/<?php echo $id; ?>" target="_blank"><?php echo $id; ?></a></p>
                <p class="citation"><b>Cite by:</b> <?php echo $article->getCitation(); ?></p>
            </footer>
        </article>
