<section id="results">
    <?php $collection = $this->collection; ?>
    <?php $articles   = $this->paginator; ?>
    <?php $title      = $collection->getName(); ?>
    <h1 class="section-title"><?php echo $title; ?></h1>
    <?php foreach($articles as $article): ?>
        <?php echo $this->partial('partials/_article-mini.phtml', array(
            'article' => $article
        )); ?>
    <?php endforeach; ?>

    <?php echo $this->paginationControl(
        $this->paginator,
        'Sliding',
        'citation/index/_pagination.phtml',
        array(
            'route' => 'citation/get',
            'id'    => $collection->getId()
        )); ?>
</section>