        <footer id="page-footer">
            <div id="FooterTwo"> © 2013 <span>kiv!</span> designers </div>
        </footer>
    </div>   <!-- #container -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
    <script src="/js/plugins.js"></script>
</body>
</html>