<?php echo $this->partial('layout/_head.phtml'); ?>
<!-- Add your site or application content here -->
<div id="container" class="twocol">
    <header id="page-header" class="clearfix">
        <div id="search-result">
            <?php echo $this->partial('forms/search-form.phtml', array(
                'query' => $this->query,
                'action' => $this->url('search')
            )); ?>
        </div> <!-- #search -->
        <h1>k<span>i</span>v<span>!</span></h1>
        <h2>Reference generator</h2>
    </header>

    <?php echo $this->content; ?>

    <section id="sidebar">
        <?php echo $this->citations(); ?>
    </section>

<?php echo $this->partial('layout/_foot.phtml');