<?php echo $this->partial('layout/_head.phtml'); ?>
    <!-- Add your site or application content here -->
<div id="container">
    <header id="page-header" class="clearfix">
        <h1>k<span>i</span>v<span>!</span></h1>
        <h2>Reference generator</h2>
    </header>
    <div id="search">
        <?php echo $this->partial('forms/search-form.phtml', array(
            'query' => $this->query,
            'action' => $this->url('search')
        )); ?>
    </div> <!-- #search -->
    <?php echo $this->content; ?>
<?php echo $this->partial('layout/_foot.phtml');