<?php echo $this->partial('layout/_head.phtml'); ?>
<div id="container">
    <header id="page-header" class="clearfix">
        <nav>
            <?php $this->navigation('Navigation')->removePage(0); ?>
            <?php echo $this->navigation('Navigation')->menu(); ?>
        </nav>
        <div id="logo">
            <h1>K<sub>V</sub></h1>
            <h2><a href="/">Reference generator</a></h2>
        </div>

        <div id="search-mini">
            <?php echo $this->partial('forms/search-form.phtml', array(
                'query' => $this->query,
                'action' => $this->url('search')
            )); ?>
        </div> <!-- #search -->
    </header>
<?php echo $this->content; ?>

<?php echo $this->partial('layout/_foot.phtml');