<?php
use Zend\Form\Form;
    /** @var Form $form */
    $form = $this->form;
    $action = $_SERVER['REQUEST_URI'];
    $form->setAttribute('action', $action);
    $form->prepare();
    echo $this->form()->openTag($form);
?>
    <p><?php echo $this->formLabel($form->get('id')); ?></p>
    <p><?php echo $this->formElement($form->get('id')); ?></p>
    <p><?php echo $this->formElementErrors($form->get('id')); ?></p>
    <p class="button-wrapper"><?php echo $this->formElement($form->get('action-open')); ?>
       <?php echo $this->formElement($form->get('action-cancel')); ?></p>
<?php echo $this->form()->closeTag(); ?>