<div id="column-wrapper" class="clearfix">
    <section class="col col1">
        <h2>By PMID</h2>
        <p>Search with PMID (the 8 digit number unique for each article) for specific article. Then generating a reference in Vancouver format is just a click away. </p>
    </section>

    <section class="col col2">
        <h2>By Text</h2>
        <p>If PMID is not known, just search using text. Multiple articles matching the search criteria will be displayed. Then the article of your choice can be selected and reference generated.</p>
    </section>

    <section class="col col3">
        <h2>Build References</h2>
        <p>You can search by PMID or text and add the generated references to your collection. Following which, you can get all the selected references as a list.</p>
    </section>
</div> <!-- column-wrapper -->