<div id="main">
    <div id="row-1" class="row clearfix">
        <div id="search-id" class="col">
            <h2>Search by Id</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed libero erat, semper ut elementum et, tempor quis nisi. Proin lobortis massa leo, ut tincidunt sem viverra ornare. In hac habitasse platea dictumst. Aenean at nisi neque. Cras scelerisque libero non elit luctus, sed lacinia urna interdum.</p>
        </div>
        <div id="search-term" class="col">
            <h2>Search by Anything else</h2>
            <p>Sed a elit diam. Sed lacinia porta leo, a tristique arcu semper vitae. Sed a sem porta, viverra quam nec, tincidunt enim. Aliquam blandit neque ut orci lacinia, at lobortis ligula dignissim. Nam enim purus, sagittis ac accumsan a, eleifend rutrum quam. Nunc tristique sagittis massa eget convallis.</p>
        </div>
    </div>
    <div id="row-2" class="row">
        <div id="vancouver" class="col">
            <h2>Citation in Vancouver</h2>
            <p>Sed fringilla malesuada elit, vel gravida sem tincidunt eu. Integer euismod diam mauris, vel sollicitudin erat faucibus in. Nullam placerat quis eros at aliquam. Donec eros dolor, posuere ultricies molestie at, semper sit amet magna. Curabitur ac nibh ornare, aliquet est ut, malesuada purus.</p>
        </div>
    </div>
    <div id="row-3" class="row clearfix">
        <div id="create-list" class="col">
            <h2>Create lists</h2>
            <p>Cras quam ante, tincidunt eget gravida nec, venenatis non nunc. Duis at arcu ut ante vestibulum scelerisque nec id lacus. Suspendisse sollicitudin, mi sit amet vestibulum fringilla, eros dui eleifend augue, quis tempor dui nulla consectetur arcu. Duis in neque malesuada, tempus metus vitae, rhoncus metus. Fusce pellentesque dui est, id elementum justo euismod nec.</p>
        </div>
        <div id="manage-lists" class="col">
            <h2>Manage lists</h2>
            <p>Cras quam ante, tincidunt eget gravida nec, venenatis non nunc. Duis at arcu ut ante vestibulum scelerisque nec id lacus. Suspendisse sollicitudin, mi sit amet vestibulum fringilla, eros dui eleifend augue, quis tempor dui nulla consectetur arcu. Duis in neque malesuada, tempus metus vitae, rhoncus metus. Fusce pellentesque dui est, id elementum justo euismod nec.</p>
        </div>
    </div>
</div>
