<div id="content">
    <div id="index">
        <div id="search">
            <h2>Search</h2>
            <p>Search Pubmed for articles. Articles can be searched by Pubmed Id (PMID), title, or authors. Sed a elit diam. Sed lacinia porta leo, a tristique arcu semper vitae. </p>
        </div>
        <div id="vancouver">
            <h2>Citation</h2>
            <p>Once the article of your choice is found, getting the reference in Vancouver format is just a "COPY" away. The reference for each article in Vancouver format is provided at the end of each article.</p>
        </div>
        <div id="save">
            <h2>Manage lists</h2>
            <p>Not just that. You can save the articles required for your research format as lists so that they can be accessed later and references generated.</p>
        </div>
    </div>
</div>
